apiVersion: v1
kind: Service
metadata:
  name: webapp-dotnet
spec:
  selector:
    app: webapp-dotnet
    tier: backend
  ports:
  - protocol: "TCP"
    port: 5106
    targetPort: 5106
  type: NodePort