name: Angular Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run workflow manually'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./dockerfiles/frontend/ --file dockerfiles/frontend/angular.Dockerfile --tag anvesh35/docker-with-dotnet:angular-v$(date +%s)

  push_to_anvesh_docker_hub:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_ANVESH }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_ANVESH }}
    # - name: Tag Docker image
    #   run: docker tag my-image-name:$(date +%s) my-docker-hub-username/my-image-name:latest
    - name: Push Docker image to Docker Hub
      run: docker push anvesh35/docker-with-dotnet:angular-v$(date +%s)
  
  push_to_srinu_docker_hub:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_SRINU }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_SRINU }}
    - name: Tag Docker image
      run: docker tag anvesh35/docker-with-dotnet:angular-v$(date +%s) tejasaisrinivaskhajjayam/docker-with-dotnet:angular-v$(date +%s)
    - name: Push Docker image to Docker Hub
      run: docker push tejasaisrinivaskhajjayam/docker-with-dotnet:angular-v$(date +%s)
  
  push_to_manasa_docker_hub:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_MANASA }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_MANASA }}
    - name: Tag Docker image
      run: docker tag anvesh35/docker-with-dotnet:angular-v$(date +%s) saimanasak/docker-with-dotnet:angular-v$(date +%s)
    - name: Push Docker image to Docker Hub
      run: docker push saimanasak/docker-with-dotnet:angular-v$(date +%s)
  
  push_to_nitish_docker_hub:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_NITISH }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_NITISH }}
    - name: Tag Docker image
      run: docker tag anvesh35/docker-with-dotnet:angular-v$(date +%s) nitishrao/docker-with-dotnet:angular-v$(date +%s)
    - name: Push Docker image to Docker Hub
      run: docker push nitishrao/docker-with-dotnet:angular-v$(date +%s)
