name: Angular Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run workflow manually'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./dockerfiles/dind/v1/ --file dockerfiles/dind/v1/Dockerfile --tag anvesh35/docker-with-dotnet:angular-v$(date +%s)

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # - name: Tag Docker image
    #   run: docker tag my-image-name:$(date +%s) my-docker-hub-username/my-image-name:latest
    - name: Push Docker image to Docker Hub
      run: docker push anvesh35/docker-with-dotnet:angular-v$(date +%s)
